// Sveriges Radio resolver.
//
// SR's web pages (sverigesradio.se) sit behind a WAF that returns 403 to our
// monitor, so scraping them is hopeless. SR does, however, publish clean,
// stable RSS/Atom for every channel's news desk via its public API at
// api.sr.se. This is exactly how the "Ekot" source works (program 83).
//
// This module maps the page URLs reporters naturally paste — e.g.
// https://www.sverigesradio.se/nyheter/p4-stockholm — to the matching
// api.sr.se program feed, so adding a P4 channel "just works".
//
// The P4 table below was generated by walking SR's own API:
//   /api/v2/channels                      -> the 25 local P4 channels
//   /api/v2/programs/index?channelid=...  -> each channel's "Nyheter P4 X" program
//   /api/rss/program/{id}                 -> verified to carry <link rel="alternate">
//                                            pointing back at the page slug below.
// (P4 Plus and P4 Södertälje have no local news desk and are intentionally absent.)

// Local-news program id per P4 channel page slug.
const P4_NEWS_PROGRAM_BY_SLUG = {
    "p4-blekinge": 105,
    "p4-dalarna": 161,
    "p4-gotland": 94,
    "p4-gavleborg": 99,
    "p4-goteborg": 104,
    "p4-halland": 128,
    "p4-jamtland": 78,
    "p4-jonkoping": 91,
    "p4-kalmar": 86,
    "p4-kristianstad": 101,
    "p4-kronoberg": 106,
    "p4-malmohus": 96,
    "p4-norrbotten": 98,
    "p4-sjuharad": 95,
    "p4-skaraborg": 97,
    "p4-stockholm": 103,
    "p4-sormland": 87,
    "p4-uppland": 114,
    "p4-varmland": 93,
    "p4-vast": 125,
    "p4-vasterbotten": 109,
    "p4-vasternorrland": 110,
    "p4-vastmanland": 112,
    "p4-orebro": 159,
    "p4-ostergotland": 160,
};

// A few national desks people also paste as plain pages.
const PROGRAM_BY_SLUG = {
    ekot: 83,
    ...P4_NEWS_PROGRAM_BY_SLUG,
};

function programFeedUrl(programId) {
    return `https://api.sr.se/api/rss/program/${programId}`;
}

// Given any URL, return a Sveriges Radio API feed when we can confidently map
// it, otherwise null. Safe to call on every add — non-SR URLs return null.
function resolveSverigesRadioFeed(rawUrl) {
    let u;
    try {
        u = new URL(rawUrl);
    } catch {
        return null;
    }
    const host = u.hostname.replace(/^www\./, "").toLowerCase();
    if (host !== "sverigesradio.se" && host !== "sr.se") return null;

    const segments = u.pathname.toLowerCase().split("/").filter(Boolean);
    // Match the channel/desk slug wherever it sits in the path, e.g.
    // /nyheter/p4-stockholm or /p4-stockholm or /ekot.
    for (const seg of segments) {
        const programId = PROGRAM_BY_SLUG[seg];
        if (programId) {
            return {
                feedUrl: programFeedUrl(programId),
                programId,
                slug: seg,
            };
        }
    }
    return null;
}

module.exports = { resolveSverigesRadioFeed, PROGRAM_BY_SLUG, P4_NEWS_PROGRAM_BY_SLUG };
