// Sveriges Radio resolver + channel catalog.
//
// SR's web pages (sverigesradio.se) sit behind a WAF that returns 403 to our
// monitor, so scraping them is hopeless. SR does, however, publish clean,
// stable RSS/Atom for every channel's news desk via its public API at
// api.sr.se. This is exactly how the "Ekot" source works (program 83).
//
// This module maps the page URLs reporters naturally paste — e.g.
// https://www.sverigesradio.se/nyheter/p4-stockholm — to the matching
// api.sr.se program feed, and exposes the full P4 catalog so the UI can offer
// one-click on/off per channel.
//
// The P4 table below was generated by walking SR's own API:
//   /api/v2/channels                      -> the 25 local P4 channels
//   /api/v2/programs/index?channelid=...  -> each channel's "Nyheter P4 X" program
//   /api/rss/program/{id}                 -> verified to carry <link rel="alternate">
//                                            pointing back at the page slug below.
// (P4 Plus and P4 Södertälje have no local news desk and are intentionally absent.)

// The 25 local P4 channels, each with its news-desk program id. `slug` is the
// last path segment of the channel's sverigesradio.se news page.
const P4_CHANNELS = [
    { slug: "p4-blekinge", name: "P4 Blekinge", programId: 105 },
    { slug: "p4-dalarna", name: "P4 Dalarna", programId: 161 },
    { slug: "p4-gotland", name: "P4 Gotland", programId: 94 },
    { slug: "p4-gavleborg", name: "P4 Gävleborg", programId: 99 },
    { slug: "p4-goteborg", name: "P4 Göteborg", programId: 104 },
    { slug: "p4-halland", name: "P4 Halland", programId: 128 },
    { slug: "p4-jamtland", name: "P4 Jämtland", programId: 78 },
    { slug: "p4-jonkoping", name: "P4 Jönköping", programId: 91 },
    { slug: "p4-kalmar", name: "P4 Kalmar", programId: 86 },
    { slug: "p4-kristianstad", name: "P4 Kristianstad", programId: 101 },
    { slug: "p4-kronoberg", name: "P4 Kronoberg", programId: 106 },
    { slug: "p4-malmohus", name: "P4 Malmöhus", programId: 96 },
    { slug: "p4-norrbotten", name: "P4 Norrbotten", programId: 98 },
    { slug: "p4-sjuharad", name: "P4 Sjuhärad", programId: 95 },
    { slug: "p4-skaraborg", name: "P4 Skaraborg", programId: 97 },
    { slug: "p4-stockholm", name: "P4 Stockholm", programId: 103 },
    { slug: "p4-sormland", name: "P4 Sörmland", programId: 87 },
    { slug: "p4-uppland", name: "P4 Uppland", programId: 114 },
    { slug: "p4-varmland", name: "P4 Värmland", programId: 93 },
    { slug: "p4-vast", name: "P4 Väst", programId: 125 },
    { slug: "p4-vasterbotten", name: "P4 Västerbotten", programId: 109 },
    { slug: "p4-vasternorrland", name: "P4 Västernorrland", programId: 110 },
    { slug: "p4-vastmanland", name: "P4 Västmanland", programId: 112 },
    { slug: "p4-orebro", name: "P4 Örebro", programId: 159 },
    { slug: "p4-ostergotland", name: "P4 Östergötland", programId: 160 },
];

function programFeedUrl(programId) {
    return `https://api.sr.se/api/rss/program/${programId}`;
}

function channelPageUrl(slug) {
    return `https://www.sverigesradio.se/nyheter/${slug}`;
}

// Catalog the UI consumes: stable slug + display name + the feed we monitor +
// the human-facing page URL (used as the source's display URL).
const P4_CATALOG = P4_CHANNELS.map((c) => ({
    slug: c.slug,
    name: c.name,
    region: c.name.replace(/^P4\s+/, ""),
    programId: c.programId,
    feedUrl: programFeedUrl(c.programId),
    pageUrl: channelPageUrl(c.slug),
}));

// Program id per page slug, including a few national desks people also paste.
const PROGRAM_BY_SLUG = {
    ekot: 83,
    ...Object.fromEntries(P4_CHANNELS.map((c) => [c.slug, c.programId])),
};

// Given any URL, return a Sveriges Radio API feed when we can confidently map
// it, otherwise null. Safe to call on every add — non-SR URLs return null.
function resolveSverigesRadioFeed(rawUrl) {
    let u;
    try {
        u = new URL(rawUrl);
    } catch {
        return null;
    }
    const host = u.hostname.replace(/^www\./, "").toLowerCase();
    if (host !== "sverigesradio.se" && host !== "sr.se") return null;

    const segments = u.pathname.toLowerCase().split("/").filter(Boolean);
    // Match the channel/desk slug wherever it sits in the path, e.g.
    // /nyheter/p4-stockholm or /p4-stockholm or /ekot.
    for (const seg of segments) {
        const programId = PROGRAM_BY_SLUG[seg];
        if (programId) {
            return { feedUrl: programFeedUrl(programId), programId, slug: seg };
        }
    }
    return null;
}

module.exports = {
    resolveSverigesRadioFeed,
    PROGRAM_BY_SLUG,
    P4_CATALOG,
};
